### ISSUE TITLE
Repeatables always buy infinite instead of one when a computable is used as the cost function

### ISSUE THREAD

**Issue by ducdat0507** [profectus-engine/Profectus#19]
Create a `Repeatable` using a `Computable` instead of a `Function`  as the cost requirement (e.g. `cost: 10` or `cost: () => 250`)
Expected behavior: The `Repeatable` buys one when there is enough resources to afford
Actual behavior: The `Repeatable` tries to buy an `Infinite` amount of itself, causing an error

**Comment by thepaperpilot** [comment]
Good catch! Should be fixed with 210c229 (accidentally typo'd when naming it - it fixes this issue, #19)
