### ISSUE TITLE
NaN error false positive when attempting to set a persistent variable to any string that starts with the letter `e`

### ISSUE THREAD

**Issue by ducdat0507** [profectus-engine/Profectus#20]
Put the following code into a layer (and include the `gameState` variable in the layer return object):
```ts
const gameState = persistent<string>("");

globalBus.on("onLoad", () => {
    gameState.value = "ended" // or any string that starts with the letter "e"
})
```
Expected behavior: The `gameState.value` is correctly set to the string `"ended"`
Actual behavior: The game falsely throws an `Error: Attempted to save NaN value to gameState` or something similar

**Comment by thepaperpilot** [comment]
That's working as intended. Persistent has a second param for whether it should nan check or not
