### ISSUE TITLE
Redundancy in save data

### ISSUE THREAD

**Issue by thepaperpilot** [profectus-engine/Profectus#8]
The save system is effectively a bottom-up state management, where each individual piece of state is put into a monolithic state object that is then serialized and deserialized. For saving, the object is constructed by traversing each layer object and adding the data marked as persistent into the save data object, in the same position. For loading, each layer is traversed and given the value at the same location in the save data object, if it exists. 

The issue comes when multiple parts of a layer both reference the same piece of persistent data. Each piece will be saved and loaded multiple times, one for each time its seen in the layers' structures. This is slightly remedied by tracking features that have already been included and skipping duplicates, but there's still significant duplication from individual pieces of state that leads to increased save file size, as well as slightly longer load times.

Perhaps this can be solved by having an object "own" the persistent data, and only the owner records the location. This has problems to solve, like the owner typically not existing when the data is created, it becoming a nuisance to project developers, and it becoming less robust to layer structure changes.

**Comment by jakub791** [comment]
Map and Set both automatically delete duplicates, right? You might use something that uses them then.

**Comment by thepaperpilot** [comment]
Jakub asked about marking the "source of truth" location, and I had these thoughts:
I'd be down for that as well. For the points example, that would mean in the returned layer object you'd write `points: persist(points)`, or something similar. I'm not a huge fan of `persist` as the name, since it'd be confusingly similar to the existing function `persistent`, but that's totally valid
that does have the issue where if I reference a property that has been marked as the source of truth, it'd have to strip away that persist call. That could probably be done in the lazy proxy though
to clarify, if I have a challenge that automatically created a persistent number for completions, I'd want it to be the source of truth, so `challenge.completions` would be marked as the source of truth. If I passed that to somewhere else, I'd have to "unmark" it
but since all features are lazy proxies, the lazy proxy could handle that in its getter

**Comment by thepaperpilot** [comment]
further conversation: https://canary.discord.com/channels/619613842141347841/1029790117075890236

**Comment by chunkybanana** [comment]
This appears to be fixed, but at the cost of reset issues.

**Comment by thepaperpilot** [comment]
Fixed by https://github.com/profectus-engine/Profectus/commit/4207677944eb38aba5c41ec9596b09ab6bea6e1c and some follow-up commits
